version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketing_system
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    image: vitkynanda/sv-ticket-service
    container_name: api_container
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: "3306"
      MYSQL_DB_NAME: ticketing_system
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./uploads:/uploads

  app:
    image: vitkynanda/sv-ticket-app
    container_name: app_container
    environment:
      NEXT_PUBLIC_BASE_API_URL: https://ticket.sharingvisionjakarta.com/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always

volumes:
  mysql_data:
