version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketing_system
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: "3306"
      MYSQL_DB_NAME: ticketing_system
    ports:
      - "8080:8080" # Ubah port sesuai kebutuhan API Anda
    depends_on:
      - mysql
    restart: always
    volumes:
      - app_uploads:/app/uploads # Sesuaikan path
      - app_logs:/app/logs # Sesuaikan path

volumes:
  mysql_data:
  app_uploads:
  app_logs:
