version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ticketing_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: vitkynanda/sv-ticket-service
    container_name: api_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./uploads:/uploads
      - ./logs:/logs

  app:
    image: vitkynanda/sv-ticket-app
    container_name: app_container
    environment:
      NEXT_PUBLIC_BASE_API_URL: https://ticket.sharingvisionjakarta.com/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always

volumes:
  postgres_data:
